-- MySQL Script generated by MySQL Workbench
-- Thu Jan 25 15:25:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` DEFAULT CHARACTER SET utf8 ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Sucursales` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(225) NOT NULL,
  `contraseña` INT NOT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `contraseña` INT NOT NULL,
  `rol` VARCHAR(45) NULL DEFAULT 'empleado',
  `sucursales_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_Sucursales1_idx` (`sucursales_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Sucursales1`
    FOREIGN KEY (`sucursales_id`)
    REFERENCES `stock`.`Sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(10) NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_table2_Categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_table2_Categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `stock`.`Categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `usuarios_id` INT NOT NULL,
  `sucursales_id` INT NOT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_Stock_Usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_Stock_Sucursales1_idx` (`sucursales_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `stock`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Sucursales1`
    FOREIGN KEY (`sucursales_id`)
    REFERENCES `stock`.`Sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Detalle_De_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Detalle_De_Stock` (
  `id_detalle_de_stock` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT 0,
  `productos_id` INT NOT NULL,
  `stock_id` INT NOT NULL,
  INDEX `fk_Productos_has_Stock_Stock1_idx` (`stock_id` ASC) VISIBLE,
  INDEX `fk_Productos_has_Stock_Productos1_idx` (`productos_id` ASC) VISIBLE,
  PRIMARY KEY (`id_detalle_de_stock`),
  CONSTRAINT `fk_Productos_has_Stock_Productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `stock`.`Productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Stock_Stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock`.`Stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Transsaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Transsaciones` (
  `id_transsaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `usuarios_id` INT NOT NULL,
  `sucursales_id` INT NOT NULL,
  PRIMARY KEY (`id_transsaciones`),
  INDEX `fk_Transsaciones_Usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_Transsaciones_Sucursales1_idx` (`sucursales_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transsaciones_Usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `stock`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transsaciones_Sucursales1`
    FOREIGN KEY (`sucursales_id`)
    REFERENCES `stock`.`Sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`Detalle_De_Transsaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`Detalle_De_Transsaciones` (
  `id_Detalle_De_Transsaciones` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT 0,
  `transsaciones_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `stock_id` INT NOT NULL,
  PRIMARY KEY (`id_Detalle_De_Transsaciones`),
  INDEX `fk_Detalle_De_Productos_Transsaciones_Transsaciones1_idx` (`transsaciones_id` ASC) VISIBLE,
  INDEX `fk_Detalle_De_Productos_Transsaciones_Productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_Detalle_De_Transsaciones_Stock1_idx` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_De_Productos_Transsaciones_Transsaciones1`
    FOREIGN KEY (`transsaciones_id`)
    REFERENCES `stock`.`Transsaciones` (`id_transsaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_De_Productos_Transsaciones_Productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `stock`.`Productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_De_Transsaciones_Stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock`.`Stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
